auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: yongpoliu.com
url: http://yongpoliu.com
feed: /atom.xml
author_info: <a href="http://yongpoliu.com/">jeffreylyp</a>
